---
- name: set the SELinux policy for the Wordpress directory
  command: semanage fcontext -a -t httpd_sys_content_t "{{ vhosts_path }}/{{ client_site_name }}(/.*)?"

- name: set the SELinux policy for wp-config.php
  command: semanage fcontext -a -t httpd_sys_script_exec_t "{{ vhosts_path }}/{{ client_site_name }}/wp-config\.php"

- name: set the SELinux policy for wp-content directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "{{ vhosts_path }}/{{ client_site_name }}/wp-content(/.*)?"

- name: set the SELinux policy for the *.php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "{{ vhosts_path }}/{{ client_site_name }}/.*\.php"

- name: set the SELinux policy for the Upgrade directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "{{ vhosts_path }}/{{ client_site_name }}/wp-content/upgrade(/.*)?"

- name: set the SELinux policy for the Uploads directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "{{ vhosts_path }}/{{ client_site_name }}/wp-content/uploads(/.*)?"

- name: set the SELinux policy for the wp-includes php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "{{ vhosts_path }}/{{ client_site_name }}/wp-includes/.*\.php"

- name: set the SELinux on all the Files
  command: restorecon -Rv "{{ vhosts_path }}/{{ client_site_name }}"

